<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReportSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $param = [
            [
                'report_date'         => '2023-12-01',
                'user_id'             => 3,
                'report_id'           => 2,
                'sub_report_id'       => 1,
                'reason_id'           => 9,
                'reason_detail'       => null,
                'shift_id'            => 1,
                'start_date'          => '2023-12-09',
                'end_date'            => null,
                'start_time'          => null,
                'end_time'            => null,
                'acquisition_days'    => 1,
                'acquisition_hours'   => 0,
                'acquisition_minutes' => 0,
                'am_pm'               => null,
                'approval1'           => 1,
                'approval2'           => 1,
                'approved'            => 1,
                'cancel'              => 0,
            ],
            [
                'report_date'         => '2023-12-02',
                'user_id'             => 5,
                'report_id'           => 1,
                'sub_report_id'       => 3,
                'reason_id'           => 8,
                'reason_detail'       => null,
                'shift_id'            => 1,
                'start_date'          => '2023-12-05',
                'end_date'            => null,
                'start_time'          => null,
                'end_time'            => null,
                'acquisition_days'    => 0.5,
                'acquisition_hours'   => 0,
                'acquisition_minutes' => 0,
                'am_pm'               => 1,
                'approval1'           => 1,
                'approval2'           => 1,
                'approved'            => 1,
                'cancel'              => 0,
            ],
            [
                'report_date'         => '2023-12-04',
                'user_id'             => 12,
                'report_id'           => 1,
                'sub_report_id'       => 1,
                'reason_id'           => 1,
                'reason_detail'       => '病院',
                'shift_id'            => 1,
                'start_date'          => '2023-12-05',
                'end_date'            => null,
                'start_time'          => null,
                'end_time'            => null,
                'acquisition_days'    => 1,
                'acquisition_hours'   => 0,
                'acquisition_minutes' => 0,
                'am_pm'               => 1,
                'approval1'           => 1,
                'approval2'           => 1,
                'approved'            => 1,
                'cancel'              => 0,
            ],
            [
                'report_date'         => '2023-12-07',
                'user_id'             => 8,
                'report_id'           => 1,
                'sub_report_id'       => 1,
                'reason_id'           => 8,
                'reason_detail'       => '子の部活の送迎',
                'shift_id'            => 1,
                'start_date'          => '2023-12-11',
                'end_date'            => null,
                'start_time'          => null,
                'end_time'            => null,
                'acquisition_days'    => 1,
                'acquisition_hours'   => 0,
                'acquisition_minutes' => 0,
                'am_pm'               => 1,
                'approval1'           => 1,
                'approval2'           => 1,
                'approved'            => 1,
                'cancel'              => 0,
            ],
            [
                'report_date'         => '2023-12-07',
                'user_id'             => 14,
                'report_id'           => 1,
                'sub_report_id'       => 3,
                'reason_id'           => 5,
                'reason_detail'       => null,
                'shift_id'            => 1,
                'start_date'          => '2023-12-10',
                'end_date'            => null,
                'start_time'          => null,
                'end_time'            => null,
                'acquisition_days'    => 0.5,
                'acquisition_hours'   => 0,
                'acquisition_minutes' => 0,
                'am_pm'               => 2,
                'approval1'           => 1,
                'approval2'           => 1,
                'approved'            => 1,
                'cancel'              => 0,
            ],
            [
                'report_date'         => '2023-12-10',
                'user_id'             => 7,
                'report_id'           => 1,
                'sub_report_id'       => 1,
                'reason_id'           => 3,
                'reason_detail'       => null,
                'shift_id'            => 1,
                'start_date'          => '2023-12-11',
                'end_date'            => null,
                'start_time'          => null,
                'end_time'            => null,
                'acquisition_days'    => 1,
                'acquisition_hours'   => 0,
                'acquisition_minutes' => 0,
                'am_pm'               => 2,
                'approval1'           => 1,
                'approval2'           => 1,
                'approved'            => 1,
                'cancel'              => 0,
            ],
            [
                'report_date'         => '2023-12-10',
                'user_id'             => 5,
                'report_id'           => 1,
                'sub_report_id'       => 3,
                'reason_id'           => 3,
                'reason_detail'       => null,
                'shift_id'            => 1,
                'start_date'          => '2023-12-11',
                'end_date'            => null,
                'start_time'          => null,
                'end_time'            => null,
                'acquisition_days'    => 1,
                'acquisition_hours'   => 0,
                'acquisition_minutes' => 0,
                'am_pm'               => 1,
                'approval1'           => 1,
                'approval2'           => 1,
                'approved'            => 1,
                'cancel'              => 0,
            ],
            [
                'report_date'         => '2023-12-10',
                'user_id'             => 1,
                'report_id'           => 1,
                'sub_report_id'       => 2,
                'reason_id'           => 2,
                'reason_detail'       => 'コロナ感染による自宅待機',
                'shift_id'            => 1,
                'start_date'          => '2023-12-11',
                'end_date'            => null,
                'start_time'          => null,
                'end_time'            => null,
                'acquisition_days'    => 1,
                'acquisition_hours'   => 0,
                'acquisition_minutes' => 0,
                'am_pm'               => null,
                'approval1'           => 1,
                'approval2'           => 1,
                'approved'            => 1,
                'cancel'              => 0,
            ],
            [
                'report_date'         => '2023-12-10',
                'user_id'             => 10,
                'report_id'           => 1,
                'sub_report_id'       => 1,
                'reason_id'           => 3,
                'reason_detail'       => null,
                'shift_id'            => 1,
                'start_date'          => '2023-12-11',
                'end_date'            => null,
                'start_time'          => null,
                'end_time'            => null,
                'acquisition_days'    => 1,
                'acquisition_hours'   => 0,
                'acquisition_minutes' => 0,
                'am_pm'               => null,
                'approval1'           => 1,
                'approval2'           => 1,
                'approved'            => 1,
                'cancel'              => 0,
            ],
            [
                'report_date'         => '2023-12-10',
                'user_id'             => 4,
                'report_id'           => 14,
                'sub_report_id'       => 4,
                'reason_id'           => 5,
                'reason_detail'       => null,
                'shift_id'            => 1,
                'start_date'          => '2023-12-11',
                'end_date'            => null,
                'start_time'          => '13:00:00',
                'end_time'            => '17:00:00',
                'acquisition_days'    => 0,
                'acquisition_hours'   => 4,
                'acquisition_minutes' => 0,
                'am_pm'               => null,
                'approval1'           => 1,
                'approval2'           => 1,
                'approved'            => 1,
                'cancel'              => 0,
            ],
            [
                'report_date'         => '2023-12-10',
                'user_id'             => 11,
                'report_id'           => 1,
                'sub_report_id'       => 1,
                'reason_id'           => 8,
                'reason_detail'       => null,
                'shift_id'            => 1,
                'start_date'          => '2023-12-11',
                'end_date'            => null,
                'start_time'          => null,
                'end_time'            => null,
                'acquisition_days'    => 1,
                'acquisition_hours'   => 0,
                'acquisition_minutes' => 0,
                'am_pm'               => null,
                'approval1'           => 1,
                'approval2'           => 1,
                'approved'            => 1,
                'cancel'              => 0,
            ],
            [
                'report_date'         => '2023-12-10',
                'user_id'             => 6,
                'report_id'           => 1,
                'sub_report_id'       => 3,
                'reason_id'           => 5,
                'reason_detail'       => '通院',
                'shift_id'            => 1,
                'start_date'          => '2023-12-11',
                'end_date'            => null,
                'start_time'          => null,
                'end_time'            => null,
                'acquisition_days'    => 1,
                'acquisition_hours'   => 0,
                'acquisition_minutes' => 0,
                'am_pm'               => null,
                'approval1'           => 1,
                'approval2'           => 1,
                'approved'            => 1,
                'cancel'              => 0,
            ],
            [
                'report_date'         => '2023-12-10',
                'user_id'             => 9,
                'report_id'           => 1,
                'sub_report_id'       => 1,
                'reason_id'           => 1,
                'reason_detail'       => '子の体調不良',
                'shift_id'            => 1,
                'start_date'          => '2023-12-11',
                'end_date'            => null,
                'start_time'          => null,
                'end_time'            => null,
                'acquisition_days'    => 1,
                'acquisition_hours'   => 0,
                'acquisition_minutes' => 0,
                'am_pm'               => null,
                'approval1'           => 1,
                'approval2'           => 1,
                'approved'            => 1,
                'cancel'              => 0,
            ],
            [
                'report_date'         => '2023-12-01',
                'user_id'             => 13,
                'report_id'           => 2,
                'sub_report_id'       => 1,
                'reason_id'           => 9,
                'reason_detail'       => null,
                'shift_id'            => 1,
                'start_date'          => '2023-12-09',
                'end_date'            => null,
                'start_time'          => null,
                'end_time'            => null,
                'acquisition_days'    => 1,
                'acquisition_hours'   => 0,
                'acquisition_minutes' => 0,
                'am_pm'               => null,
                'approval1'           => 1,
                'approval2'           => 1,
                'approved'            => 1,
                'cancel'              => 0,
            ],
            [
                'report_date'         => '2023-12-10',
                'user_id'             => 12,
                'report_id'           => 14,
                'sub_report_id'       => 4,
                'reason_id'           => 5,
                'reason_detail'       => null,
                'shift_id'            => 1,
                'start_date'          => '2023-12-11',
                'end_date'            => null,
                'start_time'          => '15:00:00',
                'end_time'            => '17:00:00',
                'acquisition_days'    => 0,
                'acquisition_hours'   => 2,
                'acquisition_minutes' => 0,
                'am_pm'               => null,
                'approval1'           => 1,
                'approval2'           => 1,
                'approved'            => 1,
                'cancel'              => 0,
            ],
            [
                'report_date'         => '2023-12-10',
                'user_id'             => 10,
                'report_id'           => 14,
                'sub_report_id'       => 4,
                'reason_id'           => 5,
                'reason_detail'       => null,
                'shift_id'            => 1,
                'start_date'          => '2023-12-11',
                'end_date'            => null,
                'start_time'          => '15:00:00',
                'end_time'            => '17:00:00',
                'acquisition_days'    => 0,
                'acquisition_hours'   => 2,
                'acquisition_minutes' => 0,
                'am_pm'               => null,
                'approval1'           => 1,
                'approval2'           => 1,
                'approved'            => 1,
                'cancel'              => 0,
            ],
            [
                'report_date'         => '2023-12-10',
                'user_id'             => 7,
                'report_id'           => 1,
                'sub_report_id'       => 3,
                'reason_id'           => 3,
                'reason_detail'       => null,
                'shift_id'            => 1,
                'start_date'          => '2023-12-11',
                'end_date'            => null,
                'start_time'          => null,
                'end_time'            => null,
                'acquisition_days'    => 1,
                'acquisition_hours'   => 0,
                'acquisition_minutes' => 0,
                'am_pm'               => 1,
                'approval1'           => 1,
                'approval2'           => 1,
                'approved'            => 1,
                'cancel'              => 0,
            ],
            [
                'report_date'         => '2023-12-10',
                'user_id'             => 8,
                'report_id'           => 1,
                'sub_report_id'       => 3,
                'reason_id'           => 3,
                'reason_detail'       => null,
                'shift_id'            => 1,
                'start_date'          => '2023-12-11',
                'end_date'            => null,
                'start_time'          => null,
                'end_time'            => null,
                'acquisition_days'    => 1,
                'acquisition_hours'   => 0,
                'acquisition_minutes' => 0,
                'am_pm'               => 2,
                'approval1'           => 1,
                'approval2'           => 1,
                'approved'            => 1,
                'cancel'              => 0,
            ],
        ];
        DB::table('reports')->insert($param);
    }
}
