<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Factory;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = Factory::create('ja_JP');
        $param = [
            [
                'name' => '小野寺　敏夫',
                // 'email' => '6@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(6),
                'employee' => 6,
                'affiliation_id' => 31,
                'adoption_date' => '1980-5-8',
                'birthday' => '02-01',
            ],
            [
                'name' => '浅野　正弘',
                // 'email' => '14@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(14),
                'employee' => 14,
                'affiliation_id' => 18,
                'adoption_date' => '1981-10-7',
                'birthday' => '01-20',
            ],
            [
                'name' => '千葉　茂',
                // 'email' => '16@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(16),
                'employee' => 16,
                'affiliation_id' => 5,
                'adoption_date' => '1983-8-17',
                'birthday' => '11-16',
            ],
            [
                'name' => '吉家 勝之',
                // 'email' => '17@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(17),
                'employee' => 17,
                'affiliation_id' => 8,
                'adoption_date' => '1984-3-21',
                'birthday' => '07-21',
            ],
            [
                'name' => '岩淵 信之',
                // 'email' => '28@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(28),
                'employee' => 28,
                'affiliation_id' => 6,
                'adoption_date' => '1989-7-21',
                'birthday' => '11-19',
            ],
            [
                'name' => '岩渕　宏',
                // 'email' => '34@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(34),
                'employee' => 34,
                'affiliation_id' => 5,
                'adoption_date' => '1991-9-11',
                'birthday' => '09-23',
            ],
            [
                'name' => '渡辺　剛',
                // 'email' => '42@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(42),
                'employee' => 42,
                'affiliation_id' => 9,
                'adoption_date' => '1994-4-1',
                'birthday' => '02-12',
            ],
            [
                'name' => '小野 裕一',
                // 'email' => '51@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(51),
                'employee' => 51,
                'affiliation_id' => 13,
                'adoption_date' => '1994-10-19',
                'birthday' => '04-02',
            ],
            [
                'name' => '山本　恵子',
                // 'email' => '63@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(63),
                'employee' => 63,
                'affiliation_id' => 11,
                'adoption_date' => '1995-4-12',
                'birthday' => '03-03',
            ],
            [
                'name' => '菅原 勝明',
                // 'email' => '68@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(68),
                'employee' => 68,
                'affiliation_id' => 9,
                'adoption_date' => '1995-6-1',
                'birthday' => '01-08',
            ],
            [
                'name' => '佐藤 欣也',
                // 'email' => '69@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(69),
                'employee' => 69,
                'affiliation_id' => 6,
                'adoption_date' => '1995-6-21',
                'birthday' => '10-14',
            ],
            [
                'name' => '沼倉　淳',
                // 'email' => '75@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(75),
                'employee' => 75,
                'affiliation_id' => 5,
                'adoption_date' => '1995-9-7',
                'birthday' => '09-10',
            ],
            [
                'name' => '岩渕 てい子',
                // 'email' => '90@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(90),
                'employee' => 90,
                'affiliation_id' => 12,
                'adoption_date' => '1995-11-13',
                'birthday' => '02-11',
            ],
            [
                'name' => '阿部 真吾',
                // 'email' => '92@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(92),
                'employee' => 92,
                'affiliation_id' => 30,
                'adoption_date' => '1996-4-1',
                'birthday' => '06-13',
            ],
            [
                'name' => '渡辺　久美',
                // 'email' => '94@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(94),
                'employee' => 94,
                'affiliation_id' => 11,
                'adoption_date' => '1996-4-1',
                'birthday' => '01-20',
            ],
            [
                'name' => '木村 勝枝',
                // 'email' => '144@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(144),
                'employee' => 144,
                'affiliation_id' => 5,
                'adoption_date' => '2001-1-21',
                'birthday' => '05-17',
            ],
            [
                'name' => '千葉 新治',
                // 'email' => '176@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(176),
                'employee' => 176,
                'affiliation_id' => 5,
                'adoption_date' => '2004-4-1',
                'birthday' => '07-27',
            ],
            [
                'name' => '菅原 富男',
                // 'email' => '177@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(177),
                'employee' => 177,
                'affiliation_id' => 8,
                'adoption_date' => '2004-7-26',
                'birthday' => '05-12',
            ],
            [
                'name' => '小岩　肇',
                // 'email' => '189@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(189),
                'employee' => 189,
                'affiliation_id' => 23,
                'adoption_date' => '2005-11-1',
                'birthday' => '10-14',
            ],
            [
                'name' => '菅原　悌',
                // 'email' => '193@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(193),
                'employee' => 193,
                'affiliation_id' => 30,
                'adoption_date' => '2006-4-3',
                'birthday' => '11-08',
            ],
            [
                'name' => '千葉　隆好',
                // 'email' => '196@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(196),
                'employee' => 196,
                'affiliation_id' => 30,
                'adoption_date' => '2006-4-3',
                'birthday' => '04-27',
            ],
            [
                'name' => '浅利　摩実',
                'email' => 'm-asari@nagashima-s.co.jp',
                'email' => 'app.sample.001@gmail.com',
                // 'email' => '201@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(201),
                'employee' => 201,
                'affiliation_id' => 14,
                'adoption_date' => '2006-7-28',
                'birthday' => '09-28',
            ],
            [
                'name' => '濁沼 さつき',
                // 'email' => '213@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(213),
                'employee' => 213,
                'affiliation_id' => 26,
                'adoption_date' => '2006-11-11',
                'birthday' => '05-05',
            ],
            [
                'name' => '千葉　寛子',
                'email' => 'h-chiba@nagashima-s.co.jp',
                'email' => 'app.sample.001@gmail.com',
                // 'email' => '214@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(214),
                'employee' => 214,
                'affiliation_id' => 14,
                'adoption_date' => '2006-11-17',
                'birthday' => '12-13',
            ],
            [
                'name' => '菅原　千春',
                // 'email' => '246@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(246),
                'employee' => 246,
                'affiliation_id' => 29,
                'adoption_date' => '2007-11-1',
                'birthday' => '01-21',
            ],
            [
                'name' => '佐藤　貴志',
                // 'email' => '248@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(248),
                'employee' => 248,
                'affiliation_id' => 22,
                'adoption_date' => '2007-11-1',
                'birthday' => '06-11',
            ],
            [
                'name' => '千葉　優二',
                // 'email' => '249@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(249),
                'employee' => 249,
                'affiliation_id' => 12,
                'adoption_date' => '2007-11-1',
                'birthday' => '10-14',
            ],
            [
                'name' => '高橋　敏春',
                // 'email' => '252@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(252),
                'employee' => 252,
                'affiliation_id' => 20,
                'adoption_date' => '2007-11-1',
                'birthday' => '02-25',
            ],
            [
                'name' => '小野寺 純',
                // 'email' => '259@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(259),
                'employee' => 259,
                'affiliation_id' => 9,
                'adoption_date' => '2007-1-24',
                'birthday' => '08-14',
            ],
            [
                'name' => '菊地　さとみ',
                // 'email' => '278@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(278),
                'employee' => 278,
                'affiliation_id' => 19,
                'adoption_date' => '2007-3-21',
                'birthday' => '05-12',
            ],
            [
                'name' => '金田 政樹',
                // 'email' => '302@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(302),
                'employee' => 302,
                'affiliation_id' => 8,
                'adoption_date' => '2007-4-23',
                'birthday' => '03-29',
            ],
            [
                'name' => '境澤　実知也',
                // 'email' => '325@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(325),
                'employee' => 325,
                'affiliation_id' => 25,
                'adoption_date' => '2007-11-26',
                'birthday' => '04-09',
            ],
            [
                'name' => '柴田 恵美子',
                // 'email' => '332@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(332),
                'employee' => 332,
                'affiliation_id' => 23,
                'adoption_date' => '2008-8-18',
                'birthday' => '08-24',
            ],
            [
                'name' => '千葉　博',
                // 'email' => '334@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(334),
                'employee' => 334,
                'affiliation_id' => 12,
                'adoption_date' => '2009-11-24',
                'birthday' => '06-25',
            ],
            [
                'name' => '永澤　祐太',
                // 'email' => '339@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(339),
                'employee' => 339,
                'affiliation_id' => 20,
                'adoption_date' => '2010-4-1',
                'birthday' => '05-01',
            ],
            [
                'name' => '鈴木 まゆみ',
                // 'email' => '363@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(363),
                'employee' => 363,
                'affiliation_id' => 26,
                'adoption_date' => '2010-12-7',
                'birthday' => '03-02',
            ],
            [
                'name' => '須藤三樹夫',
                'email' => 'm-sudou@nagashima-s.co.jp',
                'email' => 'app.sample.001@gmail.com',
                // 'email' => '366@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(366),
                'employee' => 366,
                'affiliation_id' => 14,
                'adoption_date' => '2010-12-13',
                'birthday' => '09-17',
            ],
            [
                'name' => '鈴木 立萍',
                // 'email' => '370@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(370),
                'employee' => 370,
                'affiliation_id' => 9,
                'adoption_date' => '2011-1-5',
                'birthday' => '05-10',
            ],
            [
                'name' => '三浦 　実',
                // 'email' => '383@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(383),
                'employee' => 383,
                'affiliation_id' => 5,
                'adoption_date' => '2011-8-1',
                'birthday' => '04-24',
            ],
            [
                'name' => '金野　寛子',
                // 'email' => '384@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(384),
                'employee' => 384,
                'affiliation_id' => 19,
                'adoption_date' => '2011-7-3',
                'birthday' => '07-04',
            ],
            [
                'name' => '高橋 一也',
                // 'email' => '391@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(391),
                'employee' => 391,
                'affiliation_id' => 26,
                'adoption_date' => '2011-7-30',
                'birthday' => '10-03',
            ],
            [
                'name' => '佐藤昭彦',
                // 'email' => '392@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(392),
                'employee' => 392,
                'affiliation_id' => 10,
                'adoption_date' => '2011-8-1',
                'birthday' => '07-31',
            ],
            [
                'name' => '加藤　武史',
                // 'email' => '395@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(395),
                'employee' => 395,
                'affiliation_id' => 27,
                'adoption_date' => '2011-8-1',
                'birthday' => '05-28',
            ],
            [
                'name' => '田村 和之',
                // 'email' => '397@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(397),
                'employee' => 397,
                'affiliation_id' => 9,
                'adoption_date' => '2011-8-1',
                'birthday' => '10-10',
            ],
            [
                'name' => '鈴木　和夫',
                // 'email' => '398@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(398),
                'employee' => 398,
                'affiliation_id' => 18,
                'adoption_date' => '2011-8-1',
                'birthday' => '11-27',
            ],
            [
                'name' => '伊藤　祐',
                // 'email' => '400@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(400),
                'employee' => 400,
                'affiliation_id' => 30,
                'adoption_date' => '2011-9-1',
                'birthday' => '05-22',
            ],
            [
                'name' => '伊藤　皓揮',
                // 'email' => '401@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(401),
                'employee' => 401,
                'affiliation_id' => 22,
                'adoption_date' => '2011-9-3',
                'birthday' => '06-25',
            ],
            [
                'name' => '阿部 龍磨',
                // 'email' => '406@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(406),
                'employee' => 406,
                'affiliation_id' => 31,
                'adoption_date' => '2011-11-1',
                'birthday' => '09-01',
            ],
            [
                'name' => '因幡 浩幸',
                // 'email' => '407@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(407),
                'employee' => 407,
                'affiliation_id' => 25,
                'adoption_date' => '2011-10-24',
                'birthday' => '01-25',
            ],
            [
                'name' => '佐藤　誠',
                // 'email' => '411@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(411),
                'employee' => 411,
                'affiliation_id' => 2,
                'adoption_date' => '2011-11-7',
                'birthday' => '03-31',
            ],
            [
                'name' => '阿部　敏久',
                // 'email' => '416@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(416),
                'employee' => 416,
                'affiliation_id' => 5,
                'adoption_date' => null,
                'birthday' => null,
            ],
            [
                'name' => '高野　正博',
                // 'email' => '419@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(419),
                'employee' => 419,
                'affiliation_id' => 24,
                'adoption_date' => '2011-12-5',
                'birthday' => '05-07',
            ],
            [
                'name' => '千田　りん子',
                // 'email' => '424@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(424),
                'employee' => 424,
                'affiliation_id' => 19,
                'adoption_date' => '2011-12-19',
                'birthday' => '07-27',
            ],
            [
                'name' => '佐藤　秀紀',
                // 'email' => '425@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(425),
                'employee' => 425,
                'affiliation_id' => 16,
                'adoption_date' => '2012-1-5',
                'birthday' => '06-01',
            ],
            [
                'name' => '千葉　梢',
                // 'email' => '449@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(449),
                'employee' => 449,
                'affiliation_id' => 12,
                'adoption_date' => '2012-9-1',
                'birthday' => '11-12',
            ],
            [
                'name' => '細川　純',
                // 'email' => '450@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(450),
                'employee' => 450,
                'affiliation_id' => 25,
                'adoption_date' => '2012-9-1',
                'birthday' => '10-15',
            ],
            [
                'name' => '吉田 洋次郎',
                // 'email' => '454@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(454),
                'employee' => 454,
                'affiliation_id' => 25,
                'adoption_date' => '2012-9-1',
                'birthday' => '08-07',
            ],
            [
                'name' => '岩淵 信之',
                // 'email' => '475@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(475),
                'employee' => 475,
                'affiliation_id' => 4,
                'adoption_date' => '2013-6-4',
                'birthday' => '09-20',
            ],
            [
                'name' => '菅原　巧',
                // 'email' => '482@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(482),
                'employee' => 482,
                'affiliation_id' => 30,
                'adoption_date' => '2013-8-8',
                'birthday' => '04-02',
            ],
            [
                'name' => '千葉 和俊',
                // 'email' => '488@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(488),
                'employee' => 488,
                'affiliation_id' => 13,
                'adoption_date' => '2013-10-7',
                'birthday' => '03-01',
            ],
            [
                'name' => '那須野 定',
                // 'email' => '490@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(490),
                'employee' => 490,
                'affiliation_id' => 5,
                'adoption_date' => '2013-11-1',
                'birthday' => '02-02',
            ],
            [
                'name' => '蜂谷　昭子',
                'email' => 's-shouko@nagashima-s.co.jp',
                'email' => 'app.sample.001@gmail.com',
                // 'email' => '499@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(499),
                'employee' => 499,
                'affiliation_id' => 14,
                'adoption_date' => '2013-12-1',
                'birthday' => '02-13',
            ],
            [
                'name' => '石川　勝巳',
                // 'email' => '503@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(503),
                'employee' => 503,
                'affiliation_id' => 20,
                'adoption_date' => '2014-4-1',
                'birthday' => '01-22',
            ],
            [
                'name' => '今野 祐香',
                // 'email' => '506@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(506),
                'employee' => 506,
                'affiliation_id' => 3,
                'adoption_date' => '2014-7-22',
                'birthday' => '03-12',
            ],
            [
                'name' => '菊地　和哉',
                // 'email' => '514@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(514),
                'employee' => 514,
                'affiliation_id' => 27,
                'adoption_date' => '2014-10-14',
                'birthday' => '02-26',
            ],
            [
                'name' => '長前 秀幸',
                // 'email' => '515@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(515),
                'employee' => 515,
                'affiliation_id' => 26,
                'adoption_date' => '2014-10-20',
                'birthday' => '04-30',
            ],
            [
                'name' => '大内　涼',
                // 'email' => '521@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(521),
                'employee' => 521,
                'affiliation_id' => 22,
                'adoption_date' => '2015-4-1',
                'birthday' => '06-13',
            ],
            [
                'name' => '千葉　孝',
                // 'email' => '537@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(537),
                'employee' => 537,
                'affiliation_id' => 26,
                'adoption_date' => '2015-10-5',
                'birthday' => '06-02',
            ],
            [
                'name' => '千田　瀬成',
                // 'email' => '541@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(541),
                'employee' => 541,
                'affiliation_id' => 30,
                'adoption_date' => '2016-4-1',
                'birthday' => '05-31',
            ],
            [
                'name' => '鈴木 良樹',
                // 'email' => '546@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(546),
                'employee' => 546,
                'affiliation_id' => 6,
                'adoption_date' => '2016-4-1',
                'birthday' => '08-22',
            ],
            [
                'name' => '猪岡 英宣',
                // 'email' => '552@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(552),
                'employee' => 552,
                'affiliation_id' => 6,
                'adoption_date' => '2016-9-8',
                'birthday' => '06-17',
            ],
            [
                'name' => '菊地 宏輝',
                // 'email' => '558@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(558),
                'employee' => 558,
                'affiliation_id' => 24,
                'adoption_date' => '2016-10-17',
                'birthday' => '10-22',
            ],
            [
                'name' => '菊地 嵩斗',
                // 'email' => '565@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(565),
                'employee' => 565,
                'affiliation_id' => 9,
                'adoption_date' => '2017-4-1',
                'birthday' => '05-19',
            ],
            [
                'name' => '千田　優太',
                // 'email' => '569@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(569),
                'employee' => 569,
                'affiliation_id' => 26,
                'adoption_date' => '2017-4-1',
                'birthday' => '01-20',
            ],
            [
                'name' => '佐藤　憲一',
                // 'email' => '570@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(570),
                'employee' => 570,
                'affiliation_id' => 6,
                'adoption_date' => '2017-4-1',
                'birthday' => '03-20',
            ],
            [
                'name' => '齋藤 北斗',
                // 'email' => '574@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(574),
                'employee' => 574,
                'affiliation_id' => 5,
                'adoption_date' => '2017-9-11',
                'birthday' => '12-12',
            ],
            [
                'name' => '遠藤 悦子',
                // 'email' => '575@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(575),
                'employee' => 575,
                'affiliation_id' => 8,
                'adoption_date' => '2017-11-1',
                'birthday' => '01-29',
            ],
            [
                'name' => '菅原 綾',
                // 'email' => '577@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(577),
                'employee' => 577,
                'affiliation_id' => 5,
                'adoption_date' => '2018-2-15',
                'birthday' => '10-27',
            ],
            [
                'name' => '菅原 佳己',
                // 'email' => '582@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(582),
                'employee' => 582,
                'affiliation_id' => 30,
                'adoption_date' => '2018-4-1',
                'birthday' => '10-03',
            ],
            [
                'name' => '菅原　孝春',
                // 'email' => '587@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(587),
                'employee' => 587,
                'affiliation_id' => 25,
                'adoption_date' => '2018-4-1',
                'birthday' => '03-28',
            ],
            [
                'name' => '佐藤　香奈',
                // 'email' => '588@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(588),
                'employee' => 588,
                'affiliation_id' => 25,
                'adoption_date' => '2018-4-1',
                'birthday' => '11-01',
            ],
            [
                'name' => '千葉　潤',
                // 'email' => '593@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(593),
                'employee' => 593,
                'affiliation_id' => 19,
                'adoption_date' => '2018-6-1',
                'birthday' => '07-09',
            ],
            [
                'name' => '松田　伸一',
                // 'email' => '610@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(610),
                'employee' => 610,
                'affiliation_id' => 9,
                'adoption_date' => '2019-4-1',
                'birthday' => '03-18',
            ],
            [
                'name' => '阿部　将士',
                // 'email' => '611@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(611),
                'employee' => 611,
                'affiliation_id' => 24,
                'adoption_date' => '2019-4-1',
                'birthday' => '12-13',
            ],
            [
                'name' => '小松 勇児',
                // 'email' => '613@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(613),
                'employee' => 613,
                'affiliation_id' => 6,
                'adoption_date' => '2019-6-1',
                'birthday' => '11-21',
            ],
            [
                'name' => '岩渕　昭一',
                // 'email' => '614@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(614),
                'employee' => 614,
                'affiliation_id' => 5,
                'adoption_date' => '2019-10-1',
                'birthday' => '02-24',
            ],
            [
                'name' => '菅原　麻由子',
                // 'email' => '616@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(616),
                'employee' => 616,
                'affiliation_id' => 3,
                'adoption_date' => '2019-10-1',
                'birthday' => '12-26',
            ],
            [
                'name' => '千葉　伸',
                // 'email' => '618@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(618),
                'employee' => 618,
                'affiliation_id' => 3,
                'adoption_date' => '2019-11-1',
                'birthday' => '06-25',
            ],
            [
                'name' => '岩渕　涼音',
                // 'email' => '623@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(623),
                'employee' => 623,
                'affiliation_id' => 20,
                'adoption_date' => '2020-4-1',
                'birthday' => '06-01',
            ],
            [
                'name' => '高橋　秀斗',
                // 'email' => '624@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(624),
                'employee' => 624,
                'affiliation_id' => 30,
                'adoption_date' => '2020-4-1',
                'birthday' => '01-10',
            ],
            [
                'name' => '米倉　美月',
                // 'email' => '631@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(631),
                'employee' => 631,
                'affiliation_id' => 11,
                'adoption_date' => '2020-4-1',
                'birthday' => '06-14',
            ],
            [
                'name' => '阿部　瞳',
                // 'email' => '634@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(634),
                'employee' => 634,
                'affiliation_id' => 24,
                'adoption_date' => '2020-4-1',
                'birthday' => '07-04',
            ],
            [
                'name' => '小田中 秀樹',
                // 'email' => '635@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(635),
                'employee' => 635,
                'affiliation_id' => 6,
                'adoption_date' => '2020-4-1',
                'birthday' => '03-29',
            ],
            [
                'name' => '丹野　美紗',
                // 'email' => '636@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(636),
                'employee' => 636,
                'affiliation_id' => 26,
                'adoption_date' => '2020-4-1',
                'birthday' => '09-26',
            ],
            [
                'name' => '松井　むつみ',
                'email' => 'm-matsui@nagashima-s.co.jp',
                'email' => 'app.sample.001@gmail.com',
                // 'email' => '640@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(640),
                'employee' => 640,
                'affiliation_id' => 14,
                'adoption_date' => '2020-4-13',
                'birthday' => '09-11',
            ],
            [
                'name' => '佐藤　建樹',
                // 'email' => '641@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(641),
                'employee' => 641,
                'affiliation_id' => 31,
                'adoption_date' => '2020-5-1',
                'birthday' => '06-07',
            ],
            [
                'name' => '加藤　優和',
                // 'email' => '655@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(655),
                'employee' => 655,
                'affiliation_id' => 22,
                'adoption_date' => '2021-4-1',
                'birthday' => '02-06',
            ],
            [
                'name' => '三浦　楓花',
                // 'email' => '657@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(657),
                'employee' => 657,
                'affiliation_id' => 25,
                'adoption_date' => '2021-4-1',
                'birthday' => '03-04',
            ],
            [
                'name' => '氏家　達也',
                // 'email' => '665@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(665),
                'employee' => 665,
                'affiliation_id' => 6,
                'adoption_date' => '2021-5-1',
                'birthday' => '10-06',
            ],
            [
                'name' => '高橋 悦也',
                // 'email' => '671@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(671),
                'employee' => 671,
                'affiliation_id' => 26,
                'adoption_date' => '2021-6-1',
                'birthday' => '12-24',
            ],
            [
                'name' => '丸山　善憲',
                // 'email' => '677@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(677),
                'employee' => 677,
                'affiliation_id' => 24,
                'adoption_date' => '2021-7-21',
                'birthday' => '05-20',
            ],
            [
                'name' => '沼田　庸弥',
                // 'email' => '679@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(679),
                'employee' => 679,
                'affiliation_id' => 27,
                'adoption_date' => '2021-8-1',
                'birthday' => '07-30',
            ],
            [
                'name' => '三浦　丈史',
                // 'email' => '681@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(681),
                'employee' => 681,
                'affiliation_id' => 24,
                'adoption_date' => '2021-8-16',
                'birthday' => '07-24',
            ],
            [
                'name' => '佐藤 友南',
                // 'email' => '682@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(682),
                'employee' => 682,
                'affiliation_id' => 3,
                'adoption_date' => '2021-9-1',
                'birthday' => '08-16',
            ],
            [
                'name' => '小部　裕',
                // 'email' => '683@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(683),
                'employee' => 683,
                'affiliation_id' => 30,
                'adoption_date' => '2021-9-1',
                'birthday' => '03-13',
            ],
            [
                'name' => '三宅　敏典',
                // 'email' => '687@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(687),
                'employee' => 687,
                'affiliation_id' => 27,
                'adoption_date' => '2021-11-1',
                'birthday' => '03-24',
            ],
            [
                'name' => '高橋　知也',
                // 'email' => '688@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(688),
                'employee' => 688,
                'affiliation_id' => 27,
                'adoption_date' => '2021-11-1',
                'birthday' => '09-22',
            ],
            [
                'name' => '佐藤　賢一',
                // 'email' => '693@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(693),
                'employee' => 693,
                'affiliation_id' => 25,
                'adoption_date' => '2022-2-15',
                'birthday' => '06-29',
            ],
            [
                'name' => '照井　吉次',
                // 'email' => '694@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(694),
                'employee' => 694,
                'affiliation_id' => 24,
                'adoption_date' => '2022-3-14',
                'birthday' => '06-29',
            ],
            [
                'name' => '千葉　花那',
                // 'email' => '698@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(698),
                'employee' => 698,
                'affiliation_id' => 9,
                'adoption_date' => NULL,
                'birthday' => NULL,
            ],
            [
                'name' => '鈴木　綾海',
                // 'email' => '699@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(699),
                'employee' => 699,
                'affiliation_id' => 19,
                'adoption_date' => '2022-4-1',
                'birthday' => '10-27',
            ],
            [
                'name' => '菅原　優',
                // 'email' => '701@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(701),
                'employee' => 701,
                'affiliation_id' => 29,
                'adoption_date' => '2022-4-1',
                'birthday' => '02-21',
            ],
            [
                'name' => '伊藤　雪奈',
                // 'email' => '702@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(702),
                'employee' => 702,
                'affiliation_id' => 29,
                'adoption_date' => '2022-4-1',
                'birthday' => '12-07',
            ],
            [
                'name' => '佐藤　花菜',
                // 'email' => '703@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(703),
                'employee' => 703,
                'affiliation_id' => 23,
                'adoption_date' => '2022-4-1',
                'birthday' => '10-17',
            ],
            [
                'name' => '佐藤　健治',
                // 'email' => '706@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(706),
                'employee' => 706,
                'affiliation_id' => 5,
                'adoption_date' => '2022-4-1',
                'birthday' => '09-20',
            ],
            [
                'name' => '八重樫　滉',
                // 'email' => '707@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(707),
                'employee' => 707,
                'affiliation_id' => 24,
                'adoption_date' => '2022-4-1',
                'birthday' => '01-21',
            ],
            [
                'name' => '懸田　竜馬',
                // 'email' => '708@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(708),
                'employee' => 708,
                'affiliation_id' => 27,
                'adoption_date' => '2022-5-1',
                'birthday' => '04-10',
            ],
            [
                'name' => '酒井　皇司',
                // 'email' => '709@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(709),
                'employee' => 709,
                'affiliation_id' => 24,
                'adoption_date' => '2022-5-1',
                'birthday' => '04-29',
            ],
            [
                'name' => '佐藤　渓介',
                // 'email' => '714@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(714),
                'employee' => 714,
                'affiliation_id' => 23,
                'adoption_date' => '2022-8-22',
                'birthday' => '06-18',
            ],
            [
                'name' => '西城　千香',
                // 'email' => '715@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(715),
                'employee' => 715,
                'affiliation_id' => 26,
                'adoption_date' => '2022-9-12',
                'birthday' => '09-25',
            ],
            [
                'name' => '佐々木 仁美',
                // 'email' => '716@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(716),
                'employee' => 716,
                'affiliation_id' => 25,
                'adoption_date' => '2022-9-12',
                'birthday' => '06-06',
            ],
            [
                'name' => '高橋　誠一',
                // 'email' => '721@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(721),
                'employee' => 721,
                'affiliation_id' => 27,
                'adoption_date' => '2010-3-15',
                'birthday' => '04-06',
            ],
            [
                'name' => '佐藤　由佳',
                // 'email' => '723@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(723),
                'employee' => 723,
                'affiliation_id' => 25,
                'adoption_date' => '2023-2-21',
                'birthday' => '07-20',
            ],
            [
                'name' => '熊谷琴美',
                // 'email' => '724@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(724),
                'employee' => 724,
                'affiliation_id' => 15,
                'adoption_date' => '2023-4-1',
                'birthday' => '05-13',
            ],
            [
                'name' => '佐々木陽人',
                // 'email' => '725@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(725),
                'employee' => 725,
                'affiliation_id' => 26,
                'adoption_date' => '2023-4-1',
                'birthday' => '04-05',
            ],
            [
                'name' => '小野寺美月',
                // 'email' => '726@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(726),
                'employee' => 726,
                'affiliation_id' => 26,
                'adoption_date' => '2023-4-1',
                'birthday' => '04-16',
            ],
            [
                'name' => '及川蒼依',
                // 'email' => '728@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(728),
                'employee' => 728,
                'affiliation_id' => 25,
                'adoption_date' => '2023-4-1',
                'birthday' => '07-14',
            ],
            [
                'name' => '岩渕　颯',
                // 'email' => '731@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(731),
                'employee' => 731,
                'affiliation_id' => 27,
                'adoption_date' => '2023-4-1',
                'birthday' => '11-29',
            ],
            [
                'name' => '佐藤蓮太朗',
                // 'email' => '732@mailaddress.com',
                'email' => 'app.sample.001@gmail.com',
                'password' => bcrypt(732),
                'employee' => 732,
                'affiliation_id' => 25,
                'adoption_date' => '2023-4-1',
                'birthday' => '03-09',
            ],
            // [
            //     'name' => '八重樫美菜',
            // 'email' => '733@mailaddress.com',
            //     'password' => bcrypt(733),
            //     'employee' => 733,
            // 'affiliation_id' => 15,
            //     'adoption_date' => '2023-4-1',
            //     'birthday' => NULL,
            // ],
            // [
            //     'name' => '松本英之',
            //     'email' => '734@mailaddress.com',
            //     'password' => bcrypt(734),
            //     'employee' => 734,
            // 'affiliation_id' => 15,
            //     'adoption_date' => '2023-4-1',
            //     'birthday' => NULL,
            // ],
        ];

        DB::table('users')->insert($param);
    }
}
